#!/bin/sh
set -e

./configure --debug \
    --autocrypt \
    --gnutls \
    --gpgme \
    --gsasl \
    --gss \
    --lmdb \
    --lz4 \
    --notmuch \
    --with-notmuch=/usr/include \
    --pcre2 \
    --sqlite \
    --tokyocabinet \
    --zlib \
    --zstd \
    --disable-doc \
    --locales-fix \
    --disable-nls \
    --sqlite

LOCAL=$HOME/.local
make DESTDIR=$LOCAL PKGDATADIR="$LOCAL/share/neomutt" SYSCONFDIR="$LOCAL/etc" install
